### ISSUE TITLE
Cache reset by specified db operations

### ISSUE THREAD

**Issue by dennis-dko** [go-gorm/caches#10]
## Your Question

How can I reset my cache from the memory example by specified operations like create, update and delete?

**Comment by ktsivkov** [comment]
Hey @dennis-dko,

This is a big and complex topic, but I will try to keep it as simple as possible.
_My personal opinion is that in this case I'd go with designing my application in a way that handles intervals of inconsistent data, caching the items for shorter amounts of time etc._

## Now let's look at the problem you are facing from technical perspective.
**Problem's complexity explained...**
If you really want to go to this rabbit hole, and want to invalidate the cache items for a specific entity it could easily become the mission impossible. Two main points..
1. Parsing the SQL query that is prepared to be sent to the DB, and deciding what to invalidate?
   - This requires some kind of SQL tokenizer, Parser, and logic that decides what is affected.
2. What if you have a custom SQL function defined, of which you don't have the source code?
   - This makes it almost impossible to accommodate for.

## Middle ground solution (What I'd do)
I'd write a cache invalidator that registers for the following gorm hooks (reference on how to properly register for those check this plugin's source code https://github.com/go-gorm/caches/blob/master/caches.go#L37 In here i am registering the c.Query function that wraps around (decorates) the default /gorm's/ `gorm:query` hook)
- `gorm:after_create`
- `gorm:after_update`
- `gorm:after_delete`
In those hooks I'd just invalidate all the caches generated beforehand.

As a last point do you want me to proceed with implementing such a functionality for this plugin? And if so how urgent is it for your project /so I can prioritize it accordingly/?
Otherwise feel free to contribute, ask for further assistance on this topic /or any other issues related to this project/.

**Comment by dennis-dko** [comment]
Hello thank you for your answer,

Please implement it, but what is the difference between this cache plugin and the PrepareStmt configuration flag from official GORM?

**Comment by ktsivkov** [comment]
Hi @dennis-dko , no problem, will do so!
The preparestmt flag will cache the queries locally. If the application runs in multiple pods/servers it will not share the cache between instances.

**Comment by dennis-dko** [comment]
> Hi @dennis-dko , no problem, will do so!
> The preparestmt flag will cache the queries locally. If the application runs in multiple pods/servers it will not share the cache between instances.

Ah ok, if you have implemented it, please inform me and the cache will be cleared automatically if I use GORM Create, update or delete functions, right? Like FirstOrCreate, Updates()...

**Comment by ktsivkov** [comment]
Hey @dennis-dko , please have a look at this
https://github.com/go-gorm/caches/pull/11
Examples of the implementation are added in the readme file.
### What it does:
Implements cache invalidation upon dispatching `Create`, `Update`, or `Delete` statements.
### What it doesn't do:
It does not handle Queries dispatched through `gorm.DB.Raw()`, it only covers ones done through
- `gorm.DB.Create()`
- `gorm.DB.Delete()`
- `gorm.DB.Update()`
- and `gorm.DB.Save()`
Note that go-gorm/caches/v4 is not yet publish, I will be waiting for your confirmation before I publish it.

**Comment by dennis-dko** [comment]
Hello,

I found an other error with the identifier for the cache with pointer query args.

My Example of query args to build the identifier:

![grafik](https://github.com/go-gorm/caches/assets/119768938/e695ae83-2646-4a07-a92a-6c24298ac233)

you can see the string is a pointer variable and the problem is that the pointer value will be changed on same request again like this:

![grafik](https://github.com/go-gorm/caches/assets/119768938/48a2a7dc-c0d4-4cf5-8736-baefdc197ceb)

and in the next request with the same query args (values), the string pointer variable value  shows like this:

![grafik](https://github.com/go-gorm/caches/assets/119768938/a739b78a-48e0-4a07-b2f2-d16d40f25409)

Before I can try out the invalidate function, this needs to be fixed.

**Comment by ktsivkov** [comment]
Fixed, and version 4 released
